[package]
name = "text_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
tinyfiledialogs = "3.9.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "0.36.0"
default-features = false
features = ["ttf"]
